import = [
  "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9 
blur = true

option_as_alt = "Both"

dynamic_padding = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12
