font_family CaskaydiaCove Nerd Font
font_size 13.0
scrollback_lines 2000
wheel_scroll_min_lines 1
remember_window_size yes
initial_window_width 640
initial_window_height 400
window_padding_width 5

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0.0.0
tab_bar_style powerline
tab_bar_align left
tab_powerline_style slanted
tab_activity_symbol 

# Theme
active_tab_foreground #000000
active_tab_background #eeeeee
# foreground_color #f8f8f8
# background_color #000000 
url_color #d65c9d

# Cursor
cursor #8fee96

term xterm-256color
background_opacity 0.8 

editor nvim
allow_hypoerlinks yes
confirm_os_window_close 0

